### ISSUE TITLE
Consider ignoring `last_updated` field in Terraform plan

### ISSUE THREAD

**Issue by tsolodov** [ClickHouse/terraform-provider-clickhouse#109]
TF plan often produces this change:

```
!       last_updated            = "Tuesday, 02-Jul-24 05:01:02 UTC" -> (known after apply)

```

**Comment by whites11** [comment]
I wonder why we need this field at all.
We only assign it and never read it.

Do you happen to know?

**Comment by tsolodov** [comment]
Hi @whites11. I  am not sure why it was added to TF state.

**Comment by whites11** [comment]
@Kinzeng do you maybe remember why the field was added to begin with?

**Comment by whites11** [comment]
https://github.com/ClickHouse/terraform-provider-clickhouse/pull/123 I would say if Kevin does not block us let's get rid of the field altogether

**Comment by whites11** [comment]
releases in version 0.3.0
