### ISSUE TITLE
How can  I set the ip_access to "anywhere" like is is done in the cloud console.

### ISSUE THREAD

**Issue by raphaelhohmann** [ClickHouse/terraform-provider-clickhouse#12]
In the cloud console you can set the `ip_access` to anywhere (e.g. for development databases). Can this feature also be set using this terraform provider?

**Comment by guykoh** [comment]
Thanks @raphaelhohmann  for bringing this up and for providing this example.
I created a PR to make the docs more clear - https://github.com/ClickHouse/terraform-provider-clickhouse/pull/15
