### ISSUE TITLE
Could not change scaling, Error: Provider produced inconsistent result after apply

### ISSUE THREAD

**Issue by StarpTech** [ClickHouse/terraform-provider-clickhouse#13]
Changing from

```
  idle_timeout_minutes = 60
  idle_scaling         = true
```

to

```
  idle_timeout_minutes = 0
  idle_scaling         = false
```

errored in

```
clickhouse_service.production: Modifying... [id=XXXXXXX]
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to clickhouse_service.production, provider "provider[\"registry.terraform.io/clickhouse/clickhouse\"]" produced an unexpected new value: .idle_timeout_minutes: was cty.NumberIntVal(0), but now cty.NumberIntVal(60).
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.

```
I  had to set

```
  idle_timeout_minutes = 60
  idle_scaling         = false
```

to make it work.

Also removing `idle_timeout_minutes` entirely is not possible.

**Comment by guykoh** [comment]
Hi @StarpTech, do you mind sharing more what you're trying to achieve here? Since `idle_scaling` is set to false, there's no meaning to setting the idle timeout as it is not going to idle, and that's most likely why this call is failing

**Comment by StarpTech** [comment]
Sry, I've updated the ticket. I changed from idle scaling to non-idle scaling. I was not able to do it without keeping `idle_timeout_minutes: 60` as value.

**Comment by guykoh** [comment]
I see, I still think the reason is that you change the `idle_scaling` to false, but the fact that you had to include `idle_timeout_minutes` in the payload seems like a bug - we will fix it.
Thanks for reporting this
