### ISSUE TITLE
renaming `id` property for `clickhouse_private_endpoint_registration` to `privateEndpointId`

### ISSUE THREAD

**Issue by callicles** [ClickHouse/terraform-provider-clickhouse#135]
Hi,

I have been working on https://github.com/pulumiverse/pulumi-clickhouse a pulumi provider for clickhouse cloud. 

One thing I am running into is that the bridge from terraform to pulumi is filtering properties named `id`

Ref: https://github.com/pulumi/pulumi-terraform-bridge/blob/master/pkg/tfgen/generate_schema.go#L703.

I am trying to see with the pulumi team if there is a fix, but another would be renaming this property.

I happy to make a PR here to make the change if you are open to it.

PS: if you are interested in co-maintaining the pulumi clickhouse provider, I am happy to.

**Comment by krithika-ch** [comment]
@smstone @whites11 : Do you have experience with Pulumi? would you be able to review the contribution above?

**Comment by whites11** [comment]
> @smstone @whites11 : Do you have experience with Pulumi? would you be able to review the contribution above?

@krithika-ch 

Personally I don't have experience with Pulumi.
I'd say let's keep the 2 topics separate:

- I will check if we can safely rename the property as requested
- Regarding the pulumi provider we'll have further internal discussion to decide how to move forwards

**Comment by whites11** [comment]
`id` attribute was renamed to `private_endpoint_id` in latest main branch.
Pending release

**Comment by whites11** [comment]
@callicles the attribute rename is live with version 1.0.0.

Regarding the pulumi provider, we will have internal discussions and possibly get back to you about your co-maintenance proposal.

thanks a lot

**Comment by callicles** [comment]
Thank you!

**Comment by rsickles** [comment]
Hi @callicles! The team at ClickHouse is interested in updating the [Pulumi provider](https://github.com/pulumiverse/pulumi-clickhouse) with our latest TF release. Do you know the best way for us to do this? Thanks!
