### ISSUE TITLE
Enable Database Management through the provider

### ISSUE THREAD

**Issue by callicles** [ClickHouse/terraform-provider-clickhouse#151]
I am not sure if this is in scope or not for the provider - but it would be really nice if it could be used for database management.

ie when setting up an instance - the next thing after provisioning is to setup db, users, etc... 

it would be really nice to be able to do this through terraform

**Comment by whites11** [comment]
Hello @callicles 

thanks a lot for your suggestion. We already received this feedback from other users and I can confirm this feature is in our roadmap.

Unfortunately, I can't provide any ETA at this time.
