### ISSUE TITLE
Backup configuration not implemented

### ISSUE THREAD

**Issue by lukipro** [ClickHouse/terraform-provider-clickhouse#156]
We'd like to configure backups for our Clickhouse services in Terraform.
Skimming through the source code we noticed that the `/backupConfiguration` is not implemented.
Any plans to have it anytime soon?

Thanks

**Comment by whites11** [comment]
Hello @lukipro 

Thanks for reaching out.

We currently don't have any plans to cover this feature in our terraform provider, but I will submit your request to the product team and we'll consider it for next planning phase.

cc @krithika-ch

**Comment by krithika-ch** [comment]
@lukipro : Thanks for the feedback, we will add this to the next version.

**Comment by whites11** [comment]
@lukipro release 1.2.0 of the terraform provider and it allows setting backup configuration.

**Comment by lukipro** [comment]
Awesome, that was fast :) Thanks 🍻

**Comment by lukipro** [comment]
Hate to spoil the party, but I think you used wrong validation logic for the backup config:
`backup_period_in_hours` has `["24" "48" "72" "96" "120" "144" "168" "336" "504" "672" "720"]`
`backup_retention_period_in_hours` has `["6" "8" "12" "16" "20" "24" "36" "48"]`

I guess it should be the other way around.
