### ISSUE TITLE
Expose IAM access role as a terraform attribute

### ISSUE THREAD

**Issue by manojkarthick** [ClickHouse/terraform-provider-clickhouse#16]
I'm trying to [setup S3 role based access](https://clickhouse.com/docs/en/cloud/manage/security/secure-s3) for my Clickhouse Cloud service using Terraform and I see that the IAM  role is not available as an attribute for the `clickhouse_service` resource.

![s3-role-based-iam](https://github.com/ClickHouse/terraform-provider-clickhouse/assets/7802795/ae4061f5-407e-4578-9b42-e23e3fddbcde)

This would helps us to fully automate setting up S3 access for the service. Currently we need create the service, copy the IAM role from the UI manually and setup the S3 access using terraform.

**Comment by rjoelnorgren** [comment]
Any update on this?

**Comment by Kinzeng** [comment]
hey, sorry for the late reply! do you guys just need the iamRole to be output on the terraform side so that you can reference the variable elsewhere? if so, this should be an easy fix

**Comment by manojkarthick** [comment]
yes, just available as a [terraform output](https://developer.hashicorp.com/terraform/language/values/outputs)

**Comment by Kinzeng** [comment]
ok, this should be fixed in #23

I'll try to get a release put together asap

**Comment by manojkarthick** [comment]
@Kinzeng any updates on the release?

**Comment by Kinzeng** [comment]
hi sorry for the delay. I've just released this as part of v0.0.4
please let me know if you run into any issues

**Comment by manojkarthick** [comment]
Hi @Kinzeng, I tried to use the attribute, but it seems to be null even though I can see the IAM role in the console.

```
╷
│ Error: Null value found in list
│
│   with data.aws_iam_policy_document.Clickhouse_IamPolicyDocument_7B722216,
│   on cdk.tf.json line 29, in data.aws_iam_policy_document.Clickhouse_IamPolicyDocument_7B722216.statement[0].principals[0]:
│   29:               }
│
│ Null values are not allowed for this attribute value.
```

**Comment by guykoh** [comment]
Looks like [rjoelnorgren](https://github.com/rjoelnorgren) proposed a solution, due to lack of activity on this issue, I'm closing this issue for now.
@manojkarthick feel free to reopen this issue and explain what's missing.
