### ISSUE TITLE
Backup configuration validation is wrong

### ISSUE THREAD

**Issue by lukipro** [ClickHouse/terraform-provider-clickhouse#164]
I think that wrong validation logic is used for the backup config:
`backup_period_in_hours` allows `["24" "48" "72" "96" "120" "144" "168" "336" "504" "672" "720"]`
`backup_retention_period_in_hours` allows `["6" "8" "12" "16" "20" "24" "36" "48"]`

I guess it should be the other way around.

**Comment by whites11** [comment]
:facepalm: 

fixed in release 1.2.1

thanks for raising the issue and sorry about that.
