### ISSUE TITLE
Request to update documentation

### ISSUE THREAD

**Issue by ashishtilara** [ClickHouse/terraform-provider-clickhouse#171]
took me a while to figure-out the namespace,

```
terraform {
  required_providers {
    clickhouse = {
      source = "ClickHouse/clickhouse"
    }
  }
}
```

**Comment by whites11** [comment]
Hello @ashishtilara 

the examples contain the full source as in your example.

https://github.com/ClickHouse/terraform-provider-clickhouse/blob/main/examples/full/development/aws/provider.tf#L6

could you please explain what confused you more specifically?

Thanks

**Comment by whites11** [comment]
We added the  `required_providers` field in the main example snippet for the clickhouse provider [here](https://registry.terraform.io/providers/ClickHouse/clickhouse/latest/docs#example-usage). Closing
