### ISSUE TITLE
bug: Unable to create `production` instance with `min_total_memory_gb = 12`

### ISSUE THREAD

**Issue by dilyevsky** [ClickHouse/terraform-provider-clickhouse#25]
This is the error I get on apply:

```
│ Could not create service, unexpected error: status: 400, body: {"requestId":"937f50c0-57e9-4e32-8300-4574ad1b479e","error":"BAD_REQUEST: Invalid minimum memory size: 12","status":400}
```

Setting it to 24 appears to work. Also it doesn't seem like there's a requirement of GB sizes to be multiples of 12 when configuring service via web ui (see screenshot) which is confusing.

<img width="263" alt="Screenshot 2023-11-21 at 9 40 09 AM" src="https://github.com/ClickHouse/terraform-provider-clickhouse/assets/767232/406496e1-5864-4d12-b151-719e290f3427">

**Comment by tstraley** [comment]
Min size per the documentation is 24 GiB.

The UI shown there is per replica: on that screen you find it is going to configure 3 replicas, so 3 * 8 GiB = 24 GiB which is the same minimum terraform allows.

**Comment by anjuls** [comment]
Hitting quite similar error.

```
Could not update service scaling, unexpected error: status: 400, body: {"requestId":"2c64cebf-86ca-454a-8c7b-2969eda4f1b9","error":"BAD_REQUEST: request body.minTotalMemoryGb: The value must be a multiple of 12 <number:32>","status":400}
```

**Comment by konsta-danyliuk** [comment]
Hi @anjuls 
minTotalMemoryGb is the Minimum total memory of all workers during auto-scaling in Gb. If your ClickHouse Cloud service has three replicas, the minTotalMemoryGb should be  "<desired pod memory> x 3". If you want the 32GB pod, minTotalMemoryGb should be 96.

You might want to check the https://clickhouse.com/docs/en/cloud/manage/api/services-api-reference#response-schema page for more details.

**Comment by anjuls** [comment]
Thanks , I'm able to some this now.
