### ISSUE TITLE
Issues supporting AWS Privatelink / GCP Private Svc Connect configurations

### ISSUE THREAD

**Issue by tstraley** [ClickHouse/terraform-provider-clickhouse#30]
Hi - I would like to use terraform to create a Production tier clickhouse service that is connected to my AWS VPC via privatelink, per the documentation here: https://clickhouse.com/docs/en/manage/security/aws-privatelink

I've faced numerous issues in accomplishing this, and want to share my findings for how this provider can be fixed:

## 1. `ip_access` cannot be empty array

With privatelink, we don't want any public access - only private access - so we don't want to add any IPs to this public access list. When setting `ip_access = []` the apply fails with
```
╷
│ Error: Error creating service
│ 
│   with module.clickhouse.clickhouse_service.main,
│   on ../libs/clickhouse/main.tf line 8, in resource "clickhouse_service" "main":
│    8: resource "clickhouse_service" "main" {
│ 
│ Could not create service, unexpected error: status: 400, body:
│ {"requestId":"b6e2d41a-0c59-4943-bdd9-f89511fbb38f","error":"BAD_REQUEST:
│ request body.ipAccessList value is not an array: undefined","status":400}
╵
```

As a workaround, you can assign an ip_acess source during create, and then later remove it (but then you need to deal with this issue https://github.com/ClickHouse/terraform-provider-clickhouse/issues/29)

Alternative workaround is to use something like `ip_access = [{ source = "127.0.0.1", description = "No external public access" }]` but this is obviously not ideal.

## 2. The `privateEndpointConfig` info about the service is not available in attributes

To set up privatelink, we need the `endpointServiceId` which is from the `v1/organizations/$ORG_ID/services/$INSTANCE_ID/privateEndpointConfig` API. This seems like something that could be included in the `clickhouse_service` resource read-only attributes, but it isn't.

As a workaround, can do:
```
data "http" "private_endpoint_config" {
  url = format(
    "https://api.clickhouse.cloud/v1/organizations/%s/services/%s/privateEndpointConfig",
    var.clickhouse_cloud_org_id,
    clickhouse_service.main.id
  )

  request_headers = { Authorization = local.basic_auth }
}
```

But this is obviously not ideal.

## 3. There is no way to provide the VPC endpoint ID to the org or service configuration

To establish trust and allow access from my AWS VPC, we need to add our VPC endpoint ID created for the private link to the Org config and the service.

Ideally, there would be another terraform resource to assist with this eg. `resource "clickhouse_endpoint_registration"` which would add the `privateEndpointId` to both org and service configurations. 

Note that these things are pretty equivalent for GCP Private Service Connect configuration, as well.

**Comment by Kinzeng** [comment]
thanks for the in depth info on this! I'll try to get a pr ready within the next couple days

**Comment by Kinzeng** [comment]
#35 implements points 2 and 3. I added a `clickhouse_private_endpoint_registration` resource like you suggested, and the usage looks like this:
```
resource "clickhouse_private_endpoint_registration" "private_endpoints" {
  private_endpoints = [
    {
      cloud_provider = "aws"
      id             = "vpce-abcdef12345678910" # your endpoint id here
      region         = "us-east-1" # your region here
    }
  ]
}

resource "clickhouse_service" "service" {
  name                      = "My PrivateLink Service"

  ...

  # use registered endpoint ids
  private_endpoint_ids = clickhouse_private_endpoint_registration.private_endpoints.private_endpoint_ids
}
```

point 1 will need to be fixed on the public api side of things so I'll try to get a hotfix out for that as soon as possible. please let me know if you see any issues with this implementation

**Comment by tstraley** [comment]
Thank you @Kinzeng - I appreciate the efforts to resolve these issues.

Looking at the PR implementation, I have one concern with the `private_endpoint_ids` being an attribute of the `clickhouse_service`. That makes creating the full privatelink configuration in a single terraform apply impossible, because it forms a dependency loop: The `aws_vpc_endpoint` (or GCP PSC) requires the `privateEndpointConfig` data from `clickhouse_service`, and the `private_endpoint_ids` in your `clickhouse_service` would require that `aws_vpc_endpoint` (or GCP PSC) to be created already.

To me, the endpoint registration needs to be part of a separate resource from the `clickhouse_service` as a result. What you have for `clickhouse_private_endpoint_registration` is good: maybe that resource can also take a list of `clickhouse_service_ids` to apply the endpoint IDs to in addition to the org? or maybe another `clickhouse_private_endpoint_service_attachment` needs to exist to handle this case.

**Comment by Kinzeng** [comment]
hey @tstraley, we've recently made some changes to the usage. please check out the examples [here](https://github.com/ClickHouse/terraform-provider-clickhouse/tree/main/examples/PrivateLink) and let us know if you run into any issues

**Comment by AvinashAnchula** [comment]
We are still seeing the issues after following the examples.  Below is the error message 

 Error: Error Registering ClickHouse Organization Private Endpoint IDs
│
│   with clickhouse_private_endpoint_registration.private_endpoint_aws91,
│   on chc.tf line 1, in resource "clickhouse_private_endpoint_registration" "private_endpoint_aws91":
│    1: resource "clickhouse_private_endpoint_registration" "private_endpoint_aws91" {
│
│ Could not update organization private endpoint IDs, unexpected error:
│ status: 400, body:
│ {"requestId":"b6443d48-d17f-4af9-ba52-45bef4dd7015","error":"BAD_REQUEST:
│ Invalid private endpoint list array contains non-unique
│ elements","status":400}
╵
Releasing state lock. This may take a few moments...
ERRO[0039] 1 error occurred:
	* exit status 1

**Comment by tstraley** [comment]
https://github.com/ClickHouse/terraform-provider-clickhouse/issues/48 explains why this is still not a valid Terraform configuration. It is impossible to declaratively define the state we want for the clickhouse service and aws endpoint in Terraform. Applying the example provided will only work if some clickhouse service is already deployed in the region by our org.

**Comment by egor-krv** [comment]
I am looking into this @tstraley  and I think there is a way to make clickhouse_private_endpoint_registration take accept clickhouse_service_ids or better to have clickhouse_private_endpoint_service_attachment. Should have something out in day or two.

**Comment by egor-krv** [comment]
I have implemented a separate reassure to attach the endpoints. Please take a look @tstraley and see if it work for you. I tested in my environment and it worked. I have also updated the example.
