### ISSUE TITLE
Getting 401 Error when using this provider

### ISSUE THREAD

**Issue by raphaelhohmann** [ClickHouse/terraform-provider-clickhouse#4]
Hey, this provider seems brand new, so a question before: Is it already stable? If not, just ignore this issue :).

# Bug

```
│ Error: Error creating service
│ 
│   with clickhouse_service.this,
│   on main.tf line 18, in resource "clickhouse_service" "this":
│   18: resource "clickhouse_service" "this" {
│ 
│ Could not create service, unexpected error: status: 401, body: {"error":"UNAUTHORIZED: Key is not found","status":401}
```

The weird thing is, when I use the credentials of the provider that I have created on clickhouse.cloud with the following curl, I get a `200 OK` response.

```sh
curl --silent --user $KEY:$SECRET https://api.clickhouse.cloud/v1/organizations
```

# Reproduction

I went to `clickhouse.cloud > API Keys > + New API Key`, created it and pasted the outputs to the following file.

```terraform
# main.tf
terraform {
  required_providers {
    clickhouse = {
      source  = "ClickHouse/clickhouse"
      version = "~> 0.0.2"
    }
  }
}

provider "clickhouse" {
  environment     = "staging"
  organization_id = "<org_id>"
  token_key       = "<token_key>"
  token_secret    = "<token_secret>"
}

resource "clickhouse_service" "this" {
  cloud_provider       = "aws"
  region               = var.aws_region
  name                 = "staging-service"
  tier                 = var.tier
  idle_scaling         = var.idle_scaling
  idle_timeout_minutes = var.idle_timeout_minutes
  min_total_memory_gb  = var.min_total_memory_gb
  max_total_memory_gb  = var.max_total_memory_gb
  password             = random_password.this.result
  ip_access            = [    
    {
        source      = "92.168.2.63"
        description = "Test IP"
    }
  ]
}

resource "random_password" "this" {
  length  = 32
  special = false
}
```

**Comment by raphaelhohmann** [comment]
Fixed with

```diff
provider "clickhouse" {
- environment     = "staging"
+ environment     = "production"
  organization_id = "<org_id>"
  token_key       = "<token_key>"
  token_secret    = "<token_secret>"
}
```

I was thinking this was related to the clickhouse "environments" of my organization. I suppose one should add documentation for it, so leaving this open for now.

I found the solution by investigating the source code: https://github.com/ClickHouse/terraform-provider-clickhouse/blob/774a3dc11f82401c3302621e0778dd9a6f1274ff/clickhouse/client.go#L113

**Comment by Kinzeng** [comment]
thanks for reporting this issue! yes it's meant to be stable and ready to use but it's definitely in its early stages so any and all feedback is welcome. regarding this particular issue I agree the `environment` key is confusing. it's meant for us to test against our own environments as you correctly deduced, so I think the clearest thing to do is to change it to an `api_url` key with a note that no external users are meant to use (for now)

**Comment by raphaelhohmann** [comment]
Sounds like a sound solution :), thanks for the quick reply!
