### ISSUE TITLE
configure idle_timeout_minutes for development service

### ISSUE THREAD

**Issue by cdipesa-stord** [ClickHouse/terraform-provider-clickhouse#47]
I cannot configure the idle_timeout_minutes for a development service. It is clearly configurable in the console yet I cannot do this via TF. I receive the following error when attempting to apply the TF that is attempting to set idle_timeout_minutes.

Plan: 0 to add, 1 to change, 0 to destroy.
module.clickhouse_service_nonprod.clickhouse_service.this: Modifying... [id=ac872055-7e56-4939-948a-48a3d83a5301]
╷
│ Error: Invalid Configuration
│
│   with module.clickhouse_service_nonprod.clickhouse_service.this,
│   on ../../../modules/clickhouse-service/main.tf line 1, in resource "clickhouse_service" "this":
│    1: resource "clickhouse_service" "this" {
│
│ idle_scaling, min_total_memory_gb, max_total_memory_gb, and idle_timeout_minutes cannot be defined if the service tier is development

**Comment by nikita-vanyasin** [comment]
It looks like idle_scaling should be always true for development tier. idle_timeout_minutes should be configurable according to OpenAPI schema.
min/max total memory is still available only for prod tier.
Will work on these adjustments 👌🏻

**Comment by nikita-vanyasin** [comment]
Hi @cdipesa-stord the fix should be available in next release of the provider. I'll ping here again when it is published 👌🏻

**Comment by nikita-vanyasin** [comment]
@cdipesa-stord the release [v0.2.0](https://github.com/ClickHouse/terraform-provider-clickhouse/releases/tag/v0.2.0) has been published and should fix the issue you mentioned.
