### ISSUE TITLE
clickhouse_private_endpoint_registration requires cluster to be deployed before

### ISSUE THREAD

**Issue by grzegdl** [ClickHouse/terraform-provider-clickhouse#48]
The usual pattern is to deploy dependencies first (i.e. network, PSC) & then the cluster.

`private_endpoint_config` & `private_endpoint_ids` are also part of `clickhouse_service` spec so it is expected to specify them during it's creation.

However API doesn't allow creating a PSC if there is no cluster created yet.

```
│ Error: failed get
│
│   with data.clickhouse_private_endpoint_config.regional_endpoint_config,
│   on main.tf line 23, in data "clickhouse_private_endpoint_config" "regional_endpoint_config":
│   23: data "clickhouse_private_endpoint_config" "regional_endpoint_config" {
│
│ error getting privateEndpointConfig: %!w(*errors.errorString=&{status: 400,
│ body:
│ {"requestId":"XYZ","error":"BAD_REQUEST:
│ organization has no created instances in gcp us-east1","status":400}})
```

**Comment by yardenws** [comment]
+1
Very much interrupting with managing Clickhouse via Infrastructure as code.

**Comment by nikita-vanyasin** [comment]
@egor-krv can you please check this one? I think it should have been solved with your PR (https://github.com/ClickHouse/terraform-provider-clickhouse/pull/74)

**Comment by egor-krv** [comment]
I have implemented a separate reassure to attach the endpoints. Please take a look @yardenws @grzegdl  and see if it work for you. I tested in my environment and it worked. I have also updated the example.

**Comment by yardenws** [comment]
Thanks for this egor-krv.
Which provider version was it added to?

**Comment by yardenws** [comment]
@egor-krv 
Seems like after changing to the new configuration it's destroying and re-applying the vpc endpoint everytime I'm running terraform apply.

**Comment by egor-krv** [comment]
As of removing endpoints from ClickHouse service and attaching them back or deleting endpoints in AWS? @yardenws

**Comment by yardenws** [comment]
AWS endpoint says "must to be replaced" on each time I apply. 
Also seems like some CH resources are being updated in place.

**Comment by egor-krv** [comment]
Does it work thought or it breaks ? @yardenws  I will try to retest today.

**Comment by yardenws** [comment]
Thanks Egor!
It does work, But it's being applied every time I run terraform:
Destroying the VPC Endpoint and Re-applying it, and making some changes on Clickhouse resources.

**Comment by egor-krv** [comment]
Closing this issue and created a new one https://github.com/ClickHouse/terraform-provider-clickhouse/issues/99
