### ISSUE TITLE
`clickhouse_private_endpoint_config` data with Incorrect  token_key / token_secret does not fail

### ISSUE THREAD

**Issue by tsolodov** [ClickHouse/terraform-provider-clickhouse#66]
It's trying to read data and does not fail.
```
data.clickhouse_private_endpoint_config.endpoint_config: Reading...
data.clickhouse_private_endpoint_config.endpoint_config: Still reading... [10s elapsed]
data.clickhouse_private_endpoint_config.endpoint_config: Still reading... [20s elapsed]
data.clickhouse_private_endpoint_config.endpoint_config: Still reading... [30s elapsed]
data.clickhouse_private_endpoint_config.endpoint_config: Still reading... [40s elapsed]
data.clickhouse_private_endpoint_config.endpoint_config: Still reading... [50s elapsed]
data.clickhouse_private_endpoint_config.endpoint_config: Still reading... [1m0s elapsed]
data.clickhouse_private_endpoint_config.endpoint_config: Still reading... [1m10s elapsed]
^C
Interrupt received.
Please wait for Terraform to exit or data loss may occur.
Gracefully shutting down...
```

Expected behaviour:  fail with `"requestId":"318a0751-007b-48f2-8727-2244f17b04ed","error":"UNAUTHORIZED: Key is not active","status":401` error.

**Comment by egor-krv** [comment]
Hi @tsolodov I was unable to reproduce. Can you please share your terraform code.

**Comment by tsolodov** [comment]
I used TF files from examples folder and passed expired CHC token/key.

**Comment by egor-krv** [comment]
I created a new token and let it expire and then tested again. I can see that provider code fails with 
` Error: Error Reading ClickHouse Service
│
│   with clickhouse_service.aws_red,
│   on main.tf line 28, in resource "clickhouse_service" "aws_red":
│   28: resource "clickhouse_service" "aws_red" {
│
│ Could not read ClickHouse service id 3b89: status: 401, body: {"requestId":"f73","error":"UNAUTHORIZED: Key is not active","status":401}
╵
╷
│ Error: Error Reading ClickHouse Service
│
│   with clickhouse_service.aws_blue,
│   on main.tf line 44, in resource "clickhouse_service" "aws_blue":
│   44: resource "clickhouse_service" "aws_blue" {
│
│ Could not read ClickHouse service id c94b: status: 401, body: {"requestId":"2b0","error":"UNAUTHORIZED: Key is not active","status":401}`
I can look at this again if you can let me know how to reproduce. We have made a lot of changes to the code in the past month so this might no longer be an issue.
